# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Lingua-EN-Inflect-Number
version:      1.1
version_from: Number.pm
installdirs:  site
requires:
    Lingua::EN::Inflect:           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
